platform: x64

environment:
  matrix:
    - TARGET: tournament
    - TARGET: tournament-sse42

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\bin;%PATH%
  - set MSYSTEM=MINGW64
  - bash -lc "pacman --noconfirm -S base-devel msys2-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-clang git unzip mingw-w64-x86_64-boost p7zip"

build_script:
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER; cd source/ && make $TARGET -j `nproc`"

before_test:
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER; cp source/godwhale_child.exe tests/ && mv source/godwhale_child.exe source/godwhale_child-${TARGET}.exe"

after_test:

test_script:
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER; cd tests/ && ./all.sh"

artifacts:
  - path: source/godwhale_child-${TARGET}.exe
    name: nightly_build

